executor:
  root_directory: "/tmp/${USER}_buildbuddy_remote_build"
  # docker_socket: ""
  docker_socket: "/var/run/docker.sock"
  # docker_inherit_user_ids: false
  # enable_firecracker: false
  # enableSandbox : false
  # enablePodman : false 
  app_target: "grpc://192.168.134.128:1985"
  local_cache_directory: "/tmp/buildbuddy_filecache"
  local_cache_size_bytes: 10000000000 # 10GB


